export const matchQuestionsByNumber: Record<number, string> = {
  1: "Czy obie drużyny strzelą gola?",
  2: "Czy padnie gol w pierwszej połowie?",
  3: "Czy będzie minimum 4 żółte kartki?",
  4: "Czy padnie gol po 75. minucie?",
  5: "Czy będzie minimum 10 rzutów rożnych?",
  6: "Czy zwycięzca meczu zachowa czyste konto?",
  7: "Czy padnie bramka z rzutu karnego?",
  8: "Czy do przerwy będzie remis?",
  9: "Czy padną minimum 3 gole?",
  10: "Czy będzie czerwona kartka?",
  11: "Czy obie drużyny otrzymają kartkę?",
  12: "Czy padnie gol w pierwszych 15 minutach?",
  13: "Czy będzie więcej goli w II połowie niż w I?",
  14: "Czy padnie gol po rzucie rożnym?",
  15: "Czy któraś drużyna strzeli minimum 2 gole?",
  16: "Czy będzie minimum 5 spalonych?",
  17: "Czy padnie gol w doliczonym czasie gry?",
  18: "Czy każda z drużyn drużyny wykona minimum 4 rożne?",
  19: "Czy padnie gol głową?",
  20: "Czy pierwsza połowa zakończy się wynikiem 0:0?",
  21: "Czy któryś rezerwowy zdobędzie bramkę?",
  22: "Czy będzie minimum 5 żółtych kartek?",
  23: "Czy któraś drużyna wygra różnicą minimum 2 goli?",
  24: "Czy będzie minimum 11 rzutów rożnych?",
  25: "Czy obie drużyny oddadzą celny strzał w I połowie?",
  26: "Czy padnie gol między 46. a 60. minutą?",
  27: "Czy będzie podyktowany rzut karny?",
  28: "Czy padną dokładnie 2 gole?",
  29: "Czy będzie minimum 24 fauli?",
  30: "Czy padnie gol spoza pola karnego?",
  31: "Czy padnie gol bezpośrednio po stałym fragmencie gry?",
  32: "Czy jedna drużyna będzie miała większe posiadanie piłki w jednej połowie, a druga w drugiej?",
  33: "Czy będzie więcej niż 8 celnych strzałów łącznie?",
  34: "Czy padnie gol w ciągu pierwszych 10 minut?",
  35: "Czy obie drużyny strzelą po przerwie?",
  36: "Czy będzie minimum 9 rożnych?",
  37: "Czy pierwsza kartka będzie przed 30. minutą?",
  38: "Czy padną minimum 4 gole?",
  39: "Czy któryś zawodnik zaliczy gola i asystę?",
  40: "Czy będzie remis do 60 minuty gry?",
  41: "Czy obie drużyny oddadzą minimum 3 celne strzały?",
  42: "Czy padnie gol w ostatnich 10 minutach regulaminowego czasu gry?",
  43: "Czy będzie minimum 6 żółtych kartek?",
  44: "Czy któraś drużyna zachowa czyste konto?",
  45: "Czy padnie więcej niż 1 gol w I połowie?",
  46: "Czy obie drużyny zdobędą bramkę w tej samej połowie?",
  47: "Czy będzie minimum 12 rzutów rożnych?",
  48: "Czy pierwszy gol padnie przed 30. minutą?",
  49: "Czy będzie remis po pierwszej połowie?",
  50: "Czy padnie gol bezpośrednio z rzutu wolnego?",
  51: "Czy będzie więcej goli po przerwie niż przed przerwą?",
  52: "Czy padnie gol w doliczonym czasie I połowy?",
  53: "Czy zwycięzca meczu wygra jedną bramką?",
  54: "Czy będzie minimum 7 kartek (łącznie)?",
  55: "Czy obie drużyny strzelą w ciągu 15 minut od siebie?",
  56: "Czy któraś drużyna będzie prowadzić do przerwy i nie wygra meczu?",
  57: "Czy padną minimum 3 gole w drugiej połowie?",
  58: "Czy pierwszy rzut rożny będzie przed 5. minutą?",
  59: "Czy będzie minimum 10 celnych strzałów łącznie?",
  60: "Czy padnie samobójczy gol?",
  61: "Czy obie drużyny otrzymają minimum 2 kartki?",
  62: "Czy wynik 0:0 utrzyma się przynajmniej do 30. minuty?",
  63: "Czy gol zostanie uznany po interwencji VAR?",
  64: "Czy drużyna, która pierwsza straci gola, zdobędzie później bramkę?",
  65: "Czy któryś zawodnik zakończy mecz z dwiema kartkami (czerwona po dwóch żółtych)?",
  66: "Czy padną co najmniej 2 gole w jednej połowie?",
  67: "Czy pierwsza połowa zakończy się prowadzeniem jednej z drużyn?",
  68: "Czy będzie czerwona kartka (bez sztabu i ławki)?",
  69: "Czy będzie minimum 6 minut doliczonego czasu w drugiej połowie?",
  70: "Czy zostanie podyktowany rzut karny?",
  71: "Czy sędzia pokaże pierwszą kartkę przed 20. minutą?",
  72: "Czy któryś zawodnik zdobędzie bramkę w ciągu 10 minut od wejścia z ławki?",
  73: "Czy Kanada strzeli pierwszego gola w meczu?",
  74: "Czy Niemcy wygrają mecz w regulaminowym czasie?",
  75: "Czy obie drużyny strzelą gola?",
  76: "Czy Brazylia strzeli co najmniej 2 gole?",
  77: "Czy Francja zachowa czyste konto?",
  78: "Czy Norwegia strzeli gola w pierwszej połowie?",
  79: "Czy mecz zakończy się remisem po 90 minutach?",
  80: "Czy Anglia wygra różnicą co najmniej 2 goli?",
  81: "Czy USA strzeli gola przed przerwą?",
  82: "Czy Senegal uniknie porażki w regulaminowym czasie?",
  83: "Czy padną co najmniej 3 gole?",
  84: "Czy Hiszpania będzie prowadzić do przerwy?",
  85: "Czy obie drużyny strzelą gola?",
  86: "Czy Argentyna zachowa czyste konto?",
  87: "Czy Ghana strzeli gola?",
  88: "Czy mecz będzie rozstrzygnięty po 90 minutach?",
};

export function getMatchQuestion(matchNumber: number) {
  return matchQuestionsByNumber[matchNumber] ?? "Czy padną minimum 3 gole?";
}
